var stats =
{
	title: "The Statistics of Dating",
	men: [
		{
			name:"Blake",
			platform: "Tinder",
			matched: true,
			quickUnmatch: false,
			messaged: false,
			theyMessagedFirst: false,
			chatted: false,
			obviousHookup: false,
			ghosted: false,
			datePlanned: false,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Brett",
			platform: "Tinder",
			matched: true,
			quickUnmatch: false,
			messaged: false,
			theyMessagedFirst: false,
			chatted: false,
			obviousHookup: false,
			ghosted: false,
			datePlanned: false,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Dom",
			platform: "Tinder",
			matched: true,
			quickUnmatch: false,
			messaged: false,
			theyMessagedFirst: false,
			chatted: false,
			obviousHookup: false,
			ghosted: false,
			datePlanned: false,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Emil",
			platform: "Tinder",
			matched: true,
			quickUnmatch: false,
			messaged: false,
			theyMessagedFirst: false,
			chatted: false,
			obviousHookup: false,
			ghosted: false,
			datePlanned: false,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Ford",
			platform: "Tinder",
			matched: true,
			quickUnmatch: true,
			messaged: false,
			theyMessagedFirst: false,
			chatted: false,
			obviousHookup: false,
			ghosted: false,
			datePlanned: false,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Gordon",
			platform: "Tinder",
			matched: true,
			quickUnmatch: false,
			messaged: false,
			theyMessagedFirst: false,
			chatted: false,
			obviousHookup: false,
			ghosted: false,
			datePlanned: false,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Grant",
			platform: "Tinder",
			matched: true,
			quickUnmatch: false,
			messaged: false,
			theyMessagedFirst: false,
			chatted: false,
			obviousHookup: false,
			ghosted: false,
			datePlanned: false,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Harry",
			platform: "Tinder",
			matched: true,
			quickUnmatch: false,
			messaged: false,
			theyMessagedFirst: false,
			chatted: false,
			obviousHookup: false,
			ghosted: false,
			datePlanned: false,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Jake",
			platform: "Tinder",
			matched: true,
			quickUnmatch: false,
			messaged: false,
			theyMessagedFirst: false,
			chatted: false,
			obviousHookup: false,
			ghosted: false,
			datePlanned: false,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Jarvis",
			platform: "Tinder",
			matched: true,
			quickUnmatch: true,
			messaged: false,
			theyMessagedFirst: false,
			chatted: false,
			obviousHookup: false,
			ghosted: false,
			datePlanned: false,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Jack",
			platform: "Tinder",
			matched: true,
			quickUnmatch: false,
			messaged: false,
			theyMessagedFirst: false,
			chatted: false,
			obviousHookup: false,
			ghosted: false,
			datePlanned: false,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Kirk",
			platform: "Tinder",
			matched: true,
			quickUnmatch: false,
			messaged: false,
			theyMessagedFirst: false,
			chatted: false,
			obviousHookup: false,
			ghosted: false,
			datePlanned: false,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Leo",
			platform: "Tinder",
			matched: true,
			quickUnmatch: true,
			messaged: false,
			theyMessagedFirst: false,
			chatted: false,
			obviousHookup: false,
			ghosted: false,
			datePlanned: false,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Luke",
			platform: "Tinder",
			matched: true,
			quickUnmatch: false,
			messaged: false,
			theyMessagedFirst: false,
			chatted: false,
			obviousHookup: false,
			ghosted: false,
			datePlanned: false,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Mark",
			platform: "Tinder",
			matched: true,
			quickUnmatch: false,
			messaged: false,
			theyMessagedFirst: false,
			chatted: false,
			obviousHookup: false,
			ghosted: false,
			datePlanned: false,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Matthias",
			platform: "Tinder",
			matched: true,
			quickUnmatch: false,
			messaged: false,
			theyMessagedFirst: false,
			chatted: false,
			obviousHookup: false,
			ghosted: false,
			datePlanned: false,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Neal",
			platform: "Tinder",
			matched: true,
			quickUnmatch: false,
			messaged: false,
			theyMessagedFirst: false,
			chatted: false,
			obviousHookup: false,
			ghosted: false,
			datePlanned: false,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Noah",
			platform: "Tinder",
			matched: true,
			quickUnmatch: false,
			messaged: false,
			theyMessagedFirst: false,
			chatted: false,
			obviousHookup: false,
			ghosted: false,
			datePlanned: false,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Otis",
			platform: "Tinder",
			matched: true,
			quickUnmatch: false,
			messaged: false,
			theyMessagedFirst: false,
			chatted: false,
			obviousHookup: false,
			ghosted: false,
			datePlanned: false,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Paul",
			platform: "Tinder",
			matched: true,
			quickUnmatch: true,
			messaged: false,
			theyMessagedFirst: false,
			chatted: false,
			obviousHookup: false,
			ghosted: false,
			datePlanned: false,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Peter",
			platform: "Tinder",
			matched: true,
			quickUnmatch: false,
			messaged: false,
			theyMessagedFirst: false,
			chatted: false,
			obviousHookup: false,
			ghosted: false,
			datePlanned: false,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Ryan",
			platform: "Tinder",
			matched: true,
			quickUnmatch: true,
			messaged: false,
			theyMessagedFirst: false,
			chatted: false,
			obviousHookup: false,
			ghosted: false,
			datePlanned: false,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Scott",
			platform: "Tinder",
			matched: true,
			quickUnmatch: false,
			messaged: false,
			theyMessagedFirst: false,
			chatted: false,
			obviousHookup: false,
			ghosted: false,
			datePlanned: false,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Syd",
			platform: "Tinder",
			matched: true,
			quickUnmatch: false,
			messaged: false,
			theyMessagedFirst: false,
			chatted: false,
			obviousHookup: false,
			ghosted: false,
			datePlanned: false,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Stuart",
			platform: "Tinder",
			matched: true,
			quickUnmatch: false,
			messaged: false,
			theyMessagedFirst: false,
			chatted: false,
			obviousHookup: false,
			ghosted: false,
			datePlanned: false,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Thomas",
			platform: "Tinder",
			matched: true,
			quickUnmatch: false,
			messaged: false,
			theyMessagedFirst: false,
			chatted: false,
			obviousHookup: false,
			ghosted: false,
			datePlanned: false,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Todd",
			platform: "Tinder",
			matched: true,
			quickUnmatch: false,
			messaged: false,
			theyMessagedFirst: false,
			chatted: false,
			obviousHookup: false,
			ghosted: false,
			datePlanned: false,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Uri",
			platform: "Tinder",
			matched: true,
			quickUnmatch: false,
			messaged: false,
			theyMessagedFirst: false,
			chatted: false,
			obviousHookup: false,
			ghosted: false,
			datePlanned: false,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Vernon",
			platform: "Tinder",
			matched: true,
			quickUnmatch: true,
			messaged: false,
			theyMessagedFirst: false,
			chatted: false,
			obviousHookup: false,
			ghosted: false,
			datePlanned: false,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Warren",
			platform: "Tinder",
			matched: true,
			quickUnmatch: false,
			messaged: false,
			theyMessagedFirst: false,
			chatted: false,
			obviousHookup: false,
			ghosted: false,
			datePlanned: false,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Will",
			platform: "Tinder",
			matched: true,
			quickUnmatch: false,
			messaged: false,
			theyMessagedFirst: false,
			chatted: false,
			obviousHookup: false,
			ghosted: false,
			datePlanned: false,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Page",
			platform: "Tinder",
			matched: true,
			quickUnmatch: false,
			messaged: true,
			theyMessagedFirst: true,
			chatted: true,
			obviousHookup: true,
			ghosted: false,
			datePlanned: true,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Matt",
			platform: "Tinder",
			matched: true,
			quickUnmatch: false,
			messaged: true,
			theyMessagedFirst: true,
			chatted: true,
			obviousHookup: false,
			ghosted: false,
			datePlanned: false,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Daniel",
			platform: "Tinder",
			matched: true,
			quickUnmatch: false,
			messaged: true,
			theyMessagedFirst: true,
			chatted: true,
			obviousHookup: false,
			ghosted: false,
			datePlanned: false,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Odysseus",
			platform: "Tinder",
			matched: true,
			quickUnmatch: false,
			messaged: true,
			theyMessagedFirst: true,
			chatted: true,
			obviousHookup: false,
			ghosted: false,
			datePlanned: true,
			actuallyMet: true,
			communicationProgressed: true,
			stillSeeing: true,
			loc: "Tahoe"
		},
		{
			name:"Alex",
			platform: "Tinder",
			matched: true,
			quickUnmatch: false,
			messaged: true,
			theyMessagedFirst: true,
			chatted: true,
			obviousHookup: false,
			ghosted: true,
			datePlanned: false,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Anthony",
			platform: "Tinder",
			matched: true,
			quickUnmatch: false,
			messaged: true,
			theyMessagedFirst: true,
			chatted: true,
			obviousHookup: false,
			ghosted: false,
			datePlanned: true,
			actuallyMet: true,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Jerome",
			platform: "Tinder",
			matched: true,
			quickUnmatch: false,
			messaged: true,
			theyMessagedFirst: true,
			chatted: true,
			obviousHookup: false,
			ghosted: true,
			datePlanned: false,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Kyle",
			platform: "Tinder",
			matched: true,
			quickUnmatch: false,
			messaged: true,
			theyMessagedFirst: true,
			chatted: true,
			obviousHookup: false,
			ghosted: true,
			datePlanned: true,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Andy",
			platform: "Tinder",
			matched: true,
			quickUnmatch: false,
			messaged: true,
			theyMessagedFirst: true,
			chatted: true,
			obviousHookup: false,
			ghosted: false,
			datePlanned: true,
			actuallyMet: false,
			communicationProgressed: true,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Jimmy",
			platform: "Tinder",
			matched: true,
			quickUnmatch: false,
			messaged: true,
			theyMessagedFirst: true,
			chatted: true,
			obviousHookup: false,
			ghosted: false,
			datePlanned: true,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Peter",
			platform: "Tinder",
			matched: true,
			quickUnmatch: false,
			messaged: true,
			theyMessagedFirst: true,
			chatted: true,
			obviousHookup: false,
			ghosted: false,
			datePlanned: false,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Dustin",
			platform: "Tinder",
			matched: true,
			quickUnmatch: false,
			messaged: true,
			theyMessagedFirst: true,
			chatted: true,
			obviousHookup: false,
			ghosted: false,
			datePlanned: true,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Andrew",
			platform: "Tinder",
			matched: true,
			quickUnmatch: false,
			messaged: true,
			theyMessagedFirst: true,
			chatted: true,
			obviousHookup: false,
			ghosted: false,
			datePlanned: true,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Kev",
			platform: "Tinder",
			matched: true,
			quickUnmatch: false,
			messaged: true,
			theyMessagedFirst: true,
			chatted: true,
			obviousHookup: false,
			ghosted: false,
			datePlanned: false,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Nick",
			platform: "Tinder",
			matched: true,
			quickUnmatch: false,
			messaged: true,
			theyMessagedFirst: true,
			chatted: true,
			obviousHookup: false,
			ghosted: false,
			datePlanned: false,
			actuallyMet: false,
			communicationProgressed: true,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Ian",
			platform: "Tinder",
			matched: true,
			quickUnmatch: false,
			messaged: true,
			theyMessagedFirst: true,
			chatted: true,
			obviousHookup: false,
			ghosted: true,
			datePlanned: false,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Wayne",
			platform: "Tinder",
			matched: true,
			quickUnmatch: false,
			messaged: true,
			theyMessagedFirst: true,
			chatted: true,
			obviousHookup: true,
			ghosted: true,
			datePlanned: false,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Mat",
			platform: "Tinder",
			matched: true,
			quickUnmatch: false,
			messaged: true,
			theyMessagedFirst: true,
			chatted: false,
			obviousHookup: false,
			ghosted: true,
			datePlanned: false,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"James",
			platform: "Tinder",
			matched: true,
			quickUnmatch: false,
			messaged: true,
			theyMessagedFirst: true,
			chatted: true,
			obviousHookup: true,
			ghosted: false,
			datePlanned: false,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Johnathan",
			platform: "Tinder",
			matched: true,
			quickUnmatch: false,
			messaged: false,
			theyMessagedFirst: false,
			chatted: false,
			obviousHookup: false,
			ghosted: false,
			datePlanned: false,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Jason",
			platform: "Tinder",
			matched: true,
			quickUnmatch: false,
			messaged: false,
			theyMessagedFirst: false,
			chatted: false,
			obviousHookup: false,
			ghosted: false,
			datePlanned: false,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Devin",
			platform: "Tinder",
			matched: true,
			quickUnmatch: true,
			messaged: false,
			theyMessagedFirst: false,
			chatted: false,
			obviousHookup: false,
			ghosted: false,
			datePlanned: false,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Mehrdad",
			platform: "Tinder",
			matched: true,
			quickUnmatch: false,
			messaged: true,
			theyMessagedFirst: true,
			chatted: true,
			obviousHookup: false,
			ghosted: false,
			datePlanned: false,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Rob",
			platform: "Tinder",
			matched: true,
			quickUnmatch: false,
			messaged: true,
			theyMessagedFirst: true,
			chatted: true,
			obviousHookup: false,
			ghosted: false,
			datePlanned: false,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Johnny",
			platform: "Tinder",
			matched: true,
			quickUnmatch: false,
			messaged: true,
			theyMessagedFirst: true,
			chatted: true,
			obviousHookup: false,
			ghosted: false,
			datePlanned: false,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		},
		{
			name:"Kevin",
			platform: "Tinder",
			matched: true,
			quickUnmatch: false,
			messaged: true,
			theyMessagedFirst: true,
			chatted: true,
			obviousHookup: true,
			ghosted: false,
			datePlanned: true,
			actuallyMet: false,
			communicationProgressed: false,
			stillSeeing: false,
			loc: "Tahoe"
		}
	]
}